spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.233.128:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.233.128
  rabbitmq:
    host: 192.168.233.128
    username: breeze
    password: breeze
    virtual-host: /breeze
