server:
  port: 8888
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/api/index/**
          filters:
            - RewritePath=/api(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
        - id: item-route
          uri: lb://item-service
          predicates:
            - Path=/api/item/**
          filters:
            - RewritePath=/api(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api(?<segment>.*), /$\{segment} # 重写前缀，去掉/api
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

auth:
  jwt:
    pubKeyPath: G:\\Java\\IDEA\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN