server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

auth:
  jwt:
    pubKeyPath: G:\\Java\\IDEA\\rsa\\rsa.pub # \u516C\u94A5\u5730\u5740
    priKeyPath: G:\\Java\\IDEA\\rsa\\rsa.pri # \u79C1\u94A5\u5730\u5740
    secret: breeze#$.1234+_gentle*(&(?<>
    expire: 180 # \u8FC7\u671F\u65F6\u95F4,\u5355\u4F4D\u5206\u949F
    cookieName: GMALL_TOKEN