server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

auth:
  jwt:
    pubKeyPath: G:\\Java\\IDEA\\rsa\\rsa.pub # 公钥地址
    priKeyPath: G:\\Java\\IDEA\\rsa\\rsa.pri # 私钥地址
    secret: breeze#$.1234+_gentle*(&(?<>
    expire: 180 # 过期时间
    cookieName: GMALL_TOKEN