spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.233.128:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  rabbitmq:
    host: 192.168.233.128
    username: breeze
    password: breeze
    virtual-host: /breeze
    template:
      exchange: gmall.item.exchange

